- name: Adds glusterfs client and utilities
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - glusterfs-client
    - nfs-common
    - fio

- name: Ensure the Gluster volume is mounted
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ gluster_servers[0] }}:/{{ gluster_brick_name }}"
    fstype: "{{ gluster_mount_type }}"
    opts: "{{ gluster_mount_options | default(gluster_mount_default_options[gluster_mount_type]) }}"
    state: mounted

