- name: Adds glusterfs official PPA
  apt_repository:
    repo: ppa:gluster/glusterfs-{{ gluster_version }}
  update_cache: yes

- name: Adds glusterfs client and utilities
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - glusterfs-client
    - nfs-common
    - fio

- name: Creates mount points
  file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0775') }}"
  with_items: "{{ gluster_volumes }}"

- name: Ensure the Gluster volume is mounted
  mount:
    name: "{{ item.mount_point }}"
    src: "{{ groups[gluster_servers_group][0] }}-{{ gluster_interface }}:/{{ item.name }}"
    fstype: "{{ item.mount_type }}"
    opts: "{{ item.mount_options | default(gluster_mount_default_options[item.mount_type]) }}"
    state: mounted
  with_items: "{{ gluster_volumes }}"


